version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node_container
    volumes:
    - ./src/frontend:/app
    ports:
      - 3000:3000
    # command: sh -c "cd /app/test_app && yarn start"
    tty: true

  backend:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: go_container
    volumes:
    - ./src/backend:/app
    ports:
      - 8080:8080
    # command: sh -c "go run main.go"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=test_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_container
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./src:/src
      - ./nginx_log/:/var/log/nginx

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: db_container
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_my_admin_container
    restart: on-failure
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
    links:
      - db
    ports:
      - 8000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

volumes:
  mysql-volume: