version: '3'
volumes:
  mysql-volume:
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node_container
    volumes:
    - ./src/frontend:/app
    ports:
      - ${FRONTEND_APP_PORT}:3000
    # command: sh -c "cd /app/test_app && yarn start"
    tty: true

  backend:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: go_container
    volumes:
    - ./src/backend:/app
    ports:
      - ${BACKEND_APP_PORT}:8080
    # command: sh -c "go run main.go"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=test_db
      - DB_USERNAME=test_db
      - DB_PASSWORD=test_db
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_container
    ports:
      - ${WEB_PORT}:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./src:/src
      - ./nginx_log/:/var/log/nginx

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: db_container
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_container
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    links:
      - db
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
